name: My Site
theme: jekyll-theme-cayman

title: Yorita Herrera
description: Una diseñadora aprendiendo fullstack dev
show_downloads: true
google_analytics:
gem "github-pages", group: :jekyll_plugins
